# Generated by Django 2.2 on 2019-05-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
