# Generated by Django 2.2 on 2019-05-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content1',
            new_name='content',
        ),
    ]
