# Generated by Django 2.2 on 2019-05-15 08:49

from django.db import migrations
import ueditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190515_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ueditor.models.UEditorField(default='', verbose_name='content'),
        ),
    ]
