# Generated by Django 2.2 on 2019-05-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190515_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content1',
        ),
    ]
