# Generated by Django 2.2 on 2019-05-15 08:54

from django.db import migrations
import ueditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190515_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content1',
        ),
        migrations.AddField(
            model_name='article',
            name='content2',
            field=ueditor.models.UEditorField(default='', verbose_name='content'),
        ),
    ]
