# Generated by Django 2.2 on 2019-05-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190515_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content2',
            new_name='content',
        ),
    ]
