# Generated by Django 2.2 on 2019-05-12 04:31

from django.db import migrations
import ueditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_access_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content1',
            field=ueditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
